basePath: /v1_0_0
definitions:
  timernamespace.CounterDownQuery:
    properties:
      second:
        type: integer
    type: object
  timernamespace.CounterDownResponse:
    properties:
      channelid:
        type: string
    type: object
  user.User:
    properties:
      ID:
        type: integer
      Name:
        type: string
    required:
    - ID
    type: object
  usernamespace.LinkResponse:
    properties:
      description:
        type: string
      method:
        type: string
      uri:
        type: string
    type: object
  usernamespace.UserCreateQuery:
    properties:
      Name:
        type: string
    type: object
  usernamespace.UserListResponse:
    properties:
      Description:
        type: string
      Links:
        items:
          $ref: '#/definitions/usernamespace.LinkResponse'
        type: array
      UserCount:
        type: integer
    type: object
host: localhost:5000
info:
  contact:
    email: hsz1273327@gmail.com
    name: hsz
  description: 测试
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: tp_go_gin_complex
  version: 1.0.0
paths:
  /api/user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 用户列表响应信息,会展示用户数量
          schema:
            $ref: '#/definitions/usernamespace.UserListResponse'
        "500":
          description: 服务器处理失败
          schema:
            type: string
      summary: 获取用户列表信息
      tags:
      - api user
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名信息
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/usernamespace.UserCreateQuery'
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: 请求数据不符合要求
          schema:
            type: string
        "500":
          description: 服务器处理失败
          schema:
            type: string
      summary: 创建新用户
      tags:
      - api user
  /api/user/{uid}:
    delete:
      parameters:
      - description: User ID
        in: path
        minimum: 1
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: 请求数据不符合要求
          schema:
            type: string
        "404":
          description: 未找到指定资源
          schema:
            type: string
        "500":
          description: 服务器处理失败
          schema:
            type: string
      summary: 删除指定用户
      tags:
      - api user
    get:
      parameters:
      - description: User ID
        in: path
        minimum: 1
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: 请求数据不符合要求
          schema:
            type: string
        "404":
          description: 未找到指定资源
          schema:
            type: string
      summary: 获取用户列表信息
      tags:
      - api user
    put:
      parameters:
      - description: User ID
        in: path
        minimum: 1
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: 请求数据不符合要求
          schema:
            type: string
        "404":
          description: 未找到指定资源
          schema:
            type: string
        "500":
          description: 服务器处理失败
          schema:
            type: string
      summary: 更新指定用户信息
      tags:
      - api user
  /event/timer:
    get:
      consumes:
      - application/json
      produces:
      - text/event-stream
      responses:
        "200":
          description: sse信息
          schema:
            items:
              type: string
            type: array
      summary: 创建新用户
      tags:
      - event timer
    post:
      consumes:
      - application/json
      parameters:
      - description: 倒计时信息
        in: body
        name: counterdown
        required: true
        schema:
          $ref: '#/definitions/timernamespace.CounterDownQuery'
      produces:
      - application/json
      responses:
        "200":
          description: 倒计时频道信息信息
          schema:
            $ref: '#/definitions/timernamespace.CounterDownResponse'
        "400":
          description: 请求数据不符合要求
          schema:
            type: string
        "500":
          description: 服务器处理失败
          schema:
            type: string
      summary: 创建新用户
      tags:
      - event timer
  /event/timer/{channelid}:
    get:
      parameters:
      - description: 频道id
        in: path
        name: channelid
        required: true
        type: string
      produces:
      - text/event-stream
      responses:
        "200":
          description: 用户信息"  Format(chunked)
          schema:
            items:
              type: string
            type: array
        "400":
          description: 请求数据不符合要求
          schema:
            type: string
        "404":
          description: 未找到指定资源
          schema:
            type: string
      summary: 获取用户列表信息
      tags:
      - event timer
swagger: "2.0"
